name: Setup hcloud CLI
description: Install the Hetzner Cloud CLI

runs:
  using: composite
  steps:
    - name: Install hcloud CLI
      shell: bash
      run: |
        curl -sL https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz | tar xz
        sudo mv hcloud /usr/local/bin/
